#!/bin/bash

# This is for fedora 
# ./server up: starts up Lamp server
if [ $1 = up ] 
 then
	systemctl start httpd && systemctl enable httpd
	systemctl start mariadb && systemctl enable mariadb
	
      echo " Lamp server up"

# ./server down: closes Lamp server              
elif [ $1 = down ] 
 then
	systemctl stop httpd && systemctl disable httpd
	systemctl stop mariadb && systemctl disable mariadb

      echo " Lamp server down"

else 
	echo "invald option"
fi
 exit
